#pragma once

#include "version.h"
#include "blocked_range.h"
#include "blocked_range2d.h"
#include "parallel_for.h"
#include "parallel_reduce.h"
#include "parallel_for_each.h"
#include "spin_mutex.h"
#include "task_group.h"
#include "task_arena.h"
#include "task_scheduler_init.h"
#include "global_control.h"
#include "mutex.h"
#include "parallel_pipeline.h"
